### ISSUE TITLE
poll() in ZMQ.java does not properly handle thread interruption

### ISSUE THREAD

**Issue by handersh** [zeromq/jeromq#283]
ZMQ.java:635 public static int poll(Selector selector, PollItem[] items, int count, long timeout)

Inside the while(true) loop at line 712:

```
           if (waitMillis < 0) {
                rc = selector.select(0);
            }
            else if (waitMillis == 0) {
                rc = selector.selectNow();
            }
            else {
                rc = selector.select(waitMillis);
            }
```

//////////// you should check for interrupted status on thread here... if (Thread.interrupted()) return -1;

```
            for (SelectionKey key : selector.keys()) { .. }
```

If there's no activity on the channels being selected, a thread interrupt will not have any effect and the thread will continue to stay inside poll() until the timeout is over.

SUN's javadoc for selector class (1-2 is not available for users of jeromq, handling of 3 is the issue here):

A thread blocked in one of the select() or select(long) methods may be interrupted by some other thread in one of three ways: 

•By invoking the selector's wakeup method, 

•By invoking the selector's close method, or 

•By invoking the blocked thread's interrupt method, in which case its interrupt status will be set and the selector's wakeup method will be invoked. 

Possibly more similar issues are present elsewhere in the code as the key issue is selector.select() does not seem to neccesarily throw a ClosedByInterruptException.

Tested/Reproduced on JDK1.8_0_51 on windows 7/x64.

**Comment by virtuald** [comment]
There seems to be various Thread.interrupt() issues in jeromq (for example #190), and it would be nice if #116 were resolved.

**Comment by daveyarwood** [comment]
The code referenced above is wrapped in a try-catch that [catches IOException](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/ZMQ.java#L722) and re-throws a ZError.IOException.

That's not so useful by itself because an error is still being thrown, but it at least makes it clear that we intended for those errors to bubble out and be handled by higher-level code.

Case in point: #390 was just merged today, adding a higher-level try-catch in org.zeromq.ZMQ.Poller.poll(), which catches ZError.IOExceptions (which include ClosedChannelException and ClosedByInterruptException, as mentioned above), checks to see if the context has been terminated, and stops polling gracefully.

I think my recent PRs (#386, #390) dealing with allowing the ZMQ context to manage pollers provide a way to solve issues like this. 

Here is how I think this works:

* You should use the context's `poller()` or `getPoller()` method (depending on if you're using a ZMQ.Context or a ZContext) to create a poller. This registers the poller's selector with the context so that the context can manage it.

* You should write your program in such a way that if the program is interrupted or otherwise exits, the context is terminated. For example, you could add a shutdown hook that shuts down the context.

* When the context is terminated, the selectors are closed. This triggers a ClosedChannelException the next time ZMQ.poll() is called.

* The ClosedChannelException is caught and the poll call returns 0, allowing the thread to be interrupted and the program to exit.

**Comment by daveyarwood** [comment]
(Closed by accident. I think this issue may be solved, but it would be good to have some confirmation from someone else who understands this part of the codebase!)

**Comment by daveyarwood** [comment]
I'm going to go out on a limb and say this issue is resolved -- see my explanation above.
